/**
 * Curated agent traces for the NL2SQL demo.
 *
 * The retrieval scores and generation steps illustrate the architecture and
 * reported project metrics; they are not generated by a model in this page. The
 * SQL itself is executed live by the local engine, so every result table and
 * database error on screen is computed rather than stored, including the
 * deliberately faulty first attempt in `critical-tickets`.
 */

export type RetrievedChunk = {
  table: string
  score: number
  selected: boolean
}

export type Attempt = {
  sql: string
  /** Shown as the model's stated reasoning for this attempt. */
  reasoning: string
  /** Present when the attempt is expected to fail, explaining the repair. */
  repairNote?: string
}

export type Scenario = {
  id: string
  question: string
  intent: string
  retrieval: RetrievedChunk[]
  attempts: Attempt[]
  insight: string
}

export const scenarios: Scenario[] = [
  {
    id: 'revenue-by-region',
    question: 'Which regions bring in the most completed revenue?',
    intent: 'Aggregate order totals by customer region, excluding non-completed orders.',
    retrieval: [
      { table: 'orders', score: 0.93, selected: true },
      { table: 'customers', score: 0.88, selected: true },
      { table: 'order_items', score: 0.41, selected: false },
      { table: 'products', score: 0.22, selected: false },
      { table: 'support_tickets', score: 0.14, selected: false },
    ],
    attempts: [
      {
        sql: `SELECT c.region,
       ROUND(SUM(o.amount), 2) AS revenue,
       COUNT(*) AS orders
FROM orders o
JOIN customers c ON o.customer_id = c.id
WHERE o.status = 'completed'
GROUP BY c.region
ORDER BY revenue DESC`,
        reasoning:
          'Region lives on customers, revenue on orders, so this needs a join. Filtering to completed orders keeps refunds and cancellations out of the total.',
      },
    ],
    insight:
      'Revenue concentration by region is the kind of question that used to sit in an analyst queue for days.',
  },
  {
    id: 'top-customers',
    question: 'Who are the top 5 customers by lifetime order value?',
    intent: 'Rank customers by summed completed order amount and take the top five.',
    retrieval: [
      { table: 'customers', score: 0.95, selected: true },
      { table: 'orders', score: 0.9, selected: true },
      { table: 'order_items', score: 0.38, selected: false },
      { table: 'support_tickets', score: 0.12, selected: false },
    ],
    attempts: [
      {
        sql: `SELECT c.name,
       c.plan,
       ROUND(SUM(o.amount), 2) AS lifetime_value
FROM customers c
JOIN orders o ON o.customer_id = c.id
WHERE o.status = 'completed'
GROUP BY c.name, c.plan
ORDER BY lifetime_value DESC
LIMIT 5`,
        reasoning:
          'Grouping on name and plan together keeps the plan column valid in the projection without a second pass.',
      },
    ],
    insight: 'Plan tier and spend rarely line up perfectly, which is usually the interesting part.',
  },
  {
    id: 'critical-tickets',
    question: 'How many Enterprise customers have opened a critical ticket?',
    intent: 'Count distinct Enterprise accounts with at least one critical-severity ticket.',
    retrieval: [
      { table: 'support_tickets', score: 0.91, selected: true },
      { table: 'customers', score: 0.86, selected: true },
      { table: 'orders', score: 0.29, selected: false },
      { table: 'products', score: 0.08, selected: false },
    ],
    attempts: [
      {
        sql: `SELECT COUNT(DISTINCT c.id) AS enterprise_customers
FROM customers c
JOIN support_tickets t ON t.customer_id = c.id
WHERE c.plan = 'Enterprise'
  AND t.priority = 'critical'`,
        reasoning:
          'Assumed the severity field on support_tickets is called "priority," a common guess when the retrieved schema chunk is skimmed rather than read.',
        repairNote:
          'The database rejected the column outright. The error names the offending field, so the repair node can correct it against the retrieved schema instead of guessing again.',
      },
      {
        sql: `SELECT COUNT(DISTINCT c.id) AS enterprise_customers,
       COUNT(*) AS critical_tickets
FROM customers c
JOIN support_tickets t ON t.customer_id = c.id
WHERE c.plan = 'Enterprise'
  AND t.severity = 'critical'`,
        reasoning:
          'Corrected to support_tickets.severity from the retrieved schema, and added the raw ticket count since one account can file several.',
      },
    ],
    insight:
      'This is the failure mode that matters: a plausible-looking column that does not exist. Bounded repair turns it into a correct answer instead of a wrong one.',
  },
  {
    id: 'category-units',
    question: 'Which product categories sell the most units?',
    intent: 'Sum line-item quantities per product category.',
    retrieval: [
      { table: 'order_items', score: 0.94, selected: true },
      { table: 'products', score: 0.92, selected: true },
      { table: 'orders', score: 0.44, selected: false },
      { table: 'customers', score: 0.16, selected: false },
    ],
    attempts: [
      {
        sql: `SELECT p.category,
       SUM(i.quantity) AS units_sold,
       ROUND(SUM(i.quantity * i.unit_price), 2) AS revenue
FROM order_items i
JOIN products p ON i.product_id = p.id
GROUP BY p.category
ORDER BY units_sold DESC`,
        reasoning:
          'Revenue multiplies quantity by the line-item price rather than list price, because negotiated discounts are recorded per line.',
      },
    ],
    insight: 'Unit volume and revenue rank differently. Services sell rarely but carry the total.',
  },
  {
    id: 'resolution-time',
    question: 'What is the average support resolution time by severity?',
    intent: 'Average resolution hours grouped by severity, ignoring unresolved tickets.',
    retrieval: [
      { table: 'support_tickets', score: 0.96, selected: true },
      { table: 'customers', score: 0.33, selected: false },
      { table: 'orders', score: 0.09, selected: false },
    ],
    attempts: [
      {
        sql: `SELECT severity,
       COUNT(*) AS tickets,
       COUNT(resolution_hours) AS resolved,
       ROUND(AVG(resolution_hours), 1) AS avg_hours
FROM support_tickets
GROUP BY severity
ORDER BY avg_hours`,
        reasoning:
          'AVG skips NULLs on its own, but reporting COUNT(*) beside COUNT(resolution_hours) makes it obvious how much of each bucket is still open.',
      },
    ],
    insight:
      'Showing the resolved count next to the average is what stops someone reading a fast average off a mostly-open queue.',
  },
  {
    id: 'mrr-by-plan',
    question: 'Break down monthly recurring revenue by plan.',
    intent: 'Sum MRR and count accounts per plan tier.',
    retrieval: [
      { table: 'customers', score: 0.97, selected: true },
      { table: 'orders', score: 0.24, selected: false },
      { table: 'support_tickets', score: 0.11, selected: false },
    ],
    attempts: [
      {
        sql: `SELECT plan,
       COUNT(*) AS accounts,
       SUM(mrr) AS monthly_recurring_revenue,
       ROUND(AVG(mrr), 0) AS avg_mrr
FROM customers
GROUP BY plan
ORDER BY monthly_recurring_revenue DESC`,
        reasoning:
          'Single-table aggregate. Average alongside total exposes how much of a tier is driven by a few large contracts.',
      },
    ],
    insight: 'Enterprise contracts are negotiated, so the average carries more signal than the total.',
  },
  {
    id: 'dense-regions',
    question: 'Show regions with more than 8 accounts, ranked by average MRR.',
    intent: 'Group by region, filter groups with HAVING, order by the computed average.',
    retrieval: [
      { table: 'customers', score: 0.94, selected: true },
      { table: 'orders', score: 0.21, selected: false },
    ],
    attempts: [
      {
        sql: `SELECT region,
       COUNT(*) AS accounts,
       ROUND(AVG(mrr), 0) AS avg_mrr
FROM customers
GROUP BY region
HAVING COUNT(*) > 8
ORDER BY avg_mrr DESC`,
        reasoning:
          'The account-count threshold has to run as HAVING because it filters groups after aggregation, not rows before it.',
      },
    ],
    insight: 'WHERE versus HAVING is exactly the distinction a generated query gets wrong most often.',
  },
]

export const pipelineStages = [
  { id: 'retrieve', label: 'Schema retrieval', detail: 'ChromaDB top-k' },
  { id: 'generate', label: 'SQL generation', detail: 'LLM + retrieved context' },
  { id: 'validate', label: 'Validation', detail: 'parse + schema check' },
  { id: 'execute', label: 'Execution', detail: 'live query' },
  { id: 'answer', label: 'Answer', detail: 'rows returned' },
] as const

export type StageId = (typeof pipelineStages)[number]['id']
